let
    func = FortranFunction(("sigma", String[]))
    bγ2 = ("bγ2", true)
    ω = ("wf%qed%frequencies(wf%mode)", false)
    bγ = ("bγ", true)
    d_oo = ("d_oo", true)
    bs_vo = ("bs_vo", true)
    d_vo = ("d_vo", true)
    d_ov = ("d_ov", true)
    s₁_vo = ("wf%s1", false)
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    bs_vovo = ("bs_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    d_vv = ("d_vv", true)
    t_vovo = ("t_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    bs2_vovo = ("bs2_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₁_vovo = ("s₁_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein",->", 4//1, [bγ2, ω])
    update_code!(func, ein",ii->", 4//1, [bγ, d_oo])
    update_code!(func, ein"ai,ai->", 4//1, [bs_vo, d_vo])
    update_code!(func, ein",ia,ai->", 8//1, [bγ2, d_ov, s₁_vo])
    update_code!(func, ein"ai,jb,aibj->", 4//1, [bs_vo, d_ov, u_vovo])
    update_code!(func, ein"aibj,ac,bjci->", 2//1, [bs_vovo, d_vv, t_vovo])
    update_code!(func, ein"aibj,ki,akbj->", -2//1, [bs_vovo, d_oo, t_vovo])
    update_code!(func, ein"aibj,ac,bjci->", 4//1, [bs2_vovo, d_vv, s₁_vovo])
    update_code!(func, ein"aibj,ki,akbj->", -4//1, [bs2_vovo, d_oo, s₁_vovo])
    update_code!(func, ein"aibj,kc,ak,bjci->", -4//1, [bs2_vovo, d_ov, s₁_vo, t_vovo])
    update_code!(func, ein"aibj,kc,ci,akbj->", -4//1, [bs2_vovo, d_ov, s₁_vo, t_vovo])
    finalize_eT_function(func, "jacobian_transpose_s0_2", "qed_ccsd_2")
end

