let
    func = FortranFunction(("sigma_vovo", ["v", "o", "v", "o"]))
    outperms = [[1, 2, 3, 4], [3, 4, 1, 2]]
    bs_vo = ("bs_vo", true)
    d_ov = ("d_ov", true)
    γ₂ = ("wf%s0_2", false)
    bs_vovo = ("bs_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    d_oo = ("d_oo", true)
    d_vv = ("d_vv", true)
    F_ov = ("F_ov", true)
    bs2_vovo = ("bs2_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₂_vo = ("wf%s1_2", false)
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₁_vo = ("wf%s1", false)
    γ₁ = ("wf%s0", false)
    L_ovvv = ("L_ovvv", true)
    L_ovoo = ("L_ovoo", true)
    L_ooov = ("L_ooov", true)
    L_vvov = ("L_vvov", true)
    g_ovvv = ("g_ovvv", true)
    g_ovoo = ("g_ovoo", true)
    g_ooov = ("g_ooov", true)
    g_vvov = ("g_vvov", true)
    s₂_vovo = ("s2_2", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    v₂_vovo = ("v_2_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"ai,jb->aibj", 2//1, [bs_vo, d_ov], outperms)
    update_code!(func, ein"aj,ib->aibj", -1//1, [bs_vo, d_ov], outperms)
    update_code!(func, ein"ai,jb,->aibj", 8//1, [bs_vo, d_ov, γ₂], outperms)
    update_code!(func, ein"aj,ib,->aibj", -4//1, [bs_vo, d_ov, γ₂], outperms)
    update_code!(func, ein"aibk,jk,->aibj", -2//1, [bs_vovo, d_oo, γ₂], outperms)
    update_code!(func, ein"aicj,cb,->aibj", 2//1, [bs_vovo, d_vv, γ₂], outperms)
    update_code!(func, ein"ic,akbj,ck->aibj", -2//1, [F_ov, bs2_vovo, s₂_vo], outperms)
    update_code!(func, ein"ka,bjci,ck->aibj", -2//1, [F_ov, bs2_vovo, s₂_vo], outperms)
    update_code!(func, ein"iajc,bk,ck->aibj", -1//1, [L_ovov, bs_vo, s₁_vo], outperms)
    update_code!(func, ein"iakb,cj,ck->aibj", -1//1, [L_ovov, bs_vo, s₁_vo], outperms)
    update_code!(func, ein"iakc,bj,ck->aibj", 2//1, [L_ovov, bs_vo, s₁_vo], outperms)
    update_code!(func, ein"ibkc,aj,ck->aibj", -1//1, [L_ovov, bs_vo, s₁_vo], outperms)
    update_code!(func, ein"aibk,jc,ck->aibj", -2//1, [bs_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"aicj,kb,ck->aibj", -2//1, [bs_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"aick,jb,ck->aibj", 4//1, [bs_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"ajck,ib,ck->aibj", -2//1, [bs_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"aibk,jc,ck->aibj", -2//1, [bs2_vovo, d_ov, s₁_vo], outperms)
    update_code!(func, ein"aicj,kb,ck->aibj", -2//1, [bs2_vovo, d_ov, s₁_vo], outperms)
    update_code!(func, ein"aibk,jc,ck,->aibj", -4//1, [bs2_vovo, d_ov, s₁_vo, γ₂], outperms)
    update_code!(func, ein"aicj,kb,ck,->aibj", -4//1, [bs2_vovo, d_ov, s₁_vo, γ₂], outperms)
    update_code!(func, ein"aibk,jc,ck,->aibj", -2//1, [bs2_vovo, d_ov, s₂_vo, γ₁], outperms)
    update_code!(func, ein"aicj,kb,ck,->aibj", -2//1, [bs2_vovo, d_ov, s₂_vo, γ₁], outperms)
    update_code!(func, ein"iacd,bjck,dk->aibj", 2//1, [L_ovvv, bs2_vovo, s₂_vo], outperms)
    update_code!(func, ein"iakl,bjcl,ck->aibj", -2//1, [L_ovoo, bs2_vovo, s₂_vo], outperms)
    update_code!(func, ein"iklc,akbj,cl->aibj", -2//1, [L_ooov, bs2_vovo, s₂_vo], outperms)
    update_code!(func, ein"cakd,bjci,dk->aibj", 2//1, [L_vvov, bs2_vovo, s₂_vo], outperms)
    update_code!(func, ein"ajck,ibcd,dk->aibj", -2//1, [bs2_vovo, g_ovvv, s₂_vo], outperms)
    update_code!(func, ein"ajck,iblk,cl->aibj", 2//1, [bs2_vovo, g_ovoo, s₂_vo], outperms)
    update_code!(func, ein"akbl,ikjc,cl->aibj", 2//1, [bs2_vovo, g_ooov, s₂_vo], outperms)
    update_code!(func, ein"akcj,iklb,cl->aibj", 2//1, [bs2_vovo, g_ooov, s₂_vo], outperms)
    update_code!(func, ein"akcj,idcb,dk->aibj", -2//1, [bs2_vovo, g_ovvv, s₂_vo], outperms)
    update_code!(func, ein"cidj,cakb,dk->aibj", -2//1, [bs2_vovo, g_vvov, s₂_vo], outperms)
    update_code!(func, ein"iajc,bkdl,ckdl->aibj", -2//1, [L_ovov, bs2_vovo, s₂_vovo], outperms)
    update_code!(func, ein"iakb,cjdl,ckdl->aibj", -2//1, [L_ovov, bs2_vovo, s₂_vovo], outperms)
    update_code!(func, ein"iakc,bjdl,ckdl->aibj", 2//1, [L_ovov, bs2_vovo, v₂_vovo], outperms)
    update_code!(func, ein"ajck,idlb,ckdl->aibj", 2//1, [bs2_vovo, g_ovov, s₂_vovo], outperms)
    update_code!(func, ein"akbl,icjd,ckdl->aibj", 1//1, [bs2_vovo, g_ovov, s₂_vovo], outperms)
    update_code!(func, ein"akcj,idlb,cldk->aibj", 2//1, [bs2_vovo, g_ovov, s₂_vovo], outperms)
    update_code!(func, ein"cidj,kalb,ckdl->aibj", 1//1, [bs2_vovo, g_ovov, s₂_vovo], outperms)
    update_code!(func, ein"aibk,jcld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, v₂_vovo], outperms)
    update_code!(func, ein"aicj,kbld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, v₂_vovo], outperms)
    update_code!(func, ein"ajck,ibld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, v₂_vovo], outperms)
    update_code!(func, ein"iakc,bjdl,cl,dk->aibj", -2//1, [L_ovov, bs2_vovo, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"ickd,albj,cl,dk->aibj", -2//1, [L_ovov, bs2_vovo, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"kalc,bjdi,cl,dk->aibj", -2//1, [L_ovov, bs2_vovo, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"ajck,ibld,cl,dk->aibj", 2//1, [bs2_vovo, g_ovov, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"akbl,icjd,ck,dl->aibj", 1//1, [bs2_vovo, g_ovov, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"akcj,idlb,cl,dk->aibj", 2//1, [bs2_vovo, g_ovov, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"cidj,kalb,ck,dl->aibj", 1//1, [bs2_vovo, g_ovov, s₁_vo, s₁_vo], outperms)
    finalize_eT_function(func, "jacobian_transpose_t2", "qed_ccsd_2")
end

