let
    func = FortranFunction(("sigma_vovo", ["v", "o", "v", "o"]))
    outperms = [[1, 2, 3, 4], [3, 4, 1, 2]]
    F_ov = ("F_ov", true)
    bs_vo = ("bs_vo", true)
    d_ov = ("d_ov", true)
    γ₁ = ("wf%s0", false)
    L_ovoo = ("L_ovoo", true)
    L_ovvv = ("L_ovvv", true)
    bs2_vovo = ("bs2_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    d_oo = ("d_oo", true)
    d_vv = ("d_vv", true)
    γ₂ = ("wf%s0_1", false)
    s₁_vo = ("wf%s1", false)
    s₂_vo = ("wf%s1_2", false)
    L_ooov = ("L_ooov", true)
    L_vvov = ("L_vvov", true)
    g_ovvv = ("g_ovvv", true)
    g_ovoo = ("g_ovoo", true)
    g_ooov = ("g_ooov", true)
    g_vvov = ("g_vvov", true)
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₁_vovo = ("s₁_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    v₁_vovo = ("v₁_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"ia,bj->aibj", 2//1, [F_ov, bs_vo], outperms)
    update_code!(func, ein"ib,aj->aibj", -1//1, [F_ov, bs_vo], outperms)
    update_code!(func, ein"ai,jb,->aibj", 2//1, [bs_vo, d_ov, γ₁], outperms)
    update_code!(func, ein"aj,ib,->aibj", -1//1, [bs_vo, d_ov, γ₁], outperms)
    update_code!(func, ein"iajk,bk->aibj", -1//1, [L_ovoo, bs_vo], outperms)
    update_code!(func, ein"iacb,cj->aibj", 1//1, [L_ovvv, bs_vo], outperms)
    update_code!(func, ein"aibk,jk->aibj", -2//1, [bs2_vovo, d_oo], outperms)
    update_code!(func, ein"aicj,cb->aibj", 2//1, [bs2_vovo, d_vv], outperms)
    update_code!(func, ein"aibk,jk,->aibj", -4//1, [bs2_vovo, d_oo, γ₂], outperms)
    update_code!(func, ein"aicj,cb,->aibj", 4//1, [bs2_vovo, d_vv, γ₂], outperms)
    update_code!(func, ein"ic,akbj,ck->aibj", -2//1, [F_ov, bs2_vovo, s₁_vo], outperms)
    update_code!(func, ein"ka,bjci,ck->aibj", -2//1, [F_ov, bs2_vovo, s₁_vo], outperms)
    update_code!(func, ein"aibj,kc,ck->aibj", 2//1, [bs2_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"aibk,jc,ck->aibj", -6//1, [bs2_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"aicj,kb,ck->aibj", -6//1, [bs2_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"aick,jb,ck->aibj", 8//1, [bs2_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"ajck,ib,ck->aibj", -4//1, [bs2_vovo, d_ov, s₂_vo], outperms)
    update_code!(func, ein"aibk,jc,ck,->aibj", -2//1, [bs2_vovo, d_ov, s₁_vo, γ₁], outperms)
    update_code!(func, ein"aicj,kb,ck,->aibj", -2//1, [bs2_vovo, d_ov, s₁_vo, γ₁], outperms)
    update_code!(func, ein"iacd,bjck,dk->aibj", 2//1, [L_ovvv, bs2_vovo, s₁_vo], outperms)
    update_code!(func, ein"iakl,bjcl,ck->aibj", -2//1, [L_ovoo, bs2_vovo, s₁_vo], outperms)
    update_code!(func, ein"iklc,akbj,cl->aibj", -2//1, [L_ooov, bs2_vovo, s₁_vo], outperms)
    update_code!(func, ein"cakd,bjci,dk->aibj", 2//1, [L_vvov, bs2_vovo, s₁_vo], outperms)
    update_code!(func, ein"ajck,ibcd,dk->aibj", -2//1, [bs2_vovo, g_ovvv, s₁_vo], outperms)
    update_code!(func, ein"ajck,iblk,cl->aibj", 2//1, [bs2_vovo, g_ovoo, s₁_vo], outperms)
    update_code!(func, ein"akbl,ikjc,cl->aibj", 2//1, [bs2_vovo, g_ooov, s₁_vo], outperms)
    update_code!(func, ein"akcj,iklb,cl->aibj", 2//1, [bs2_vovo, g_ooov, s₁_vo], outperms)
    update_code!(func, ein"akcj,idcb,dk->aibj", -2//1, [bs2_vovo, g_ovvv, s₁_vo], outperms)
    update_code!(func, ein"cidj,cakb,dk->aibj", -2//1, [bs2_vovo, g_vvov, s₁_vo], outperms)
    update_code!(func, ein"iajc,bkdl,ckdl->aibj", -2//1, [L_ovov, bs2_vovo, s₁_vovo], outperms)
    update_code!(func, ein"iakb,cjdl,ckdl->aibj", -2//1, [L_ovov, bs2_vovo, s₁_vovo], outperms)
    update_code!(func, ein"iakc,bjdl,ckdl->aibj", 2//1, [L_ovov, bs2_vovo, v₁_vovo], outperms)
    update_code!(func, ein"ajck,idlb,ckdl->aibj", 2//1, [bs2_vovo, g_ovov, s₁_vovo], outperms)
    update_code!(func, ein"akbl,icjd,ckdl->aibj", 1//1, [bs2_vovo, g_ovov, s₁_vovo], outperms)
    update_code!(func, ein"akcj,idlb,cldk->aibj", 2//1, [bs2_vovo, g_ovov, s₁_vovo], outperms)
    update_code!(func, ein"cidj,kalb,ckdl->aibj", 1//1, [bs2_vovo, g_ovov, s₁_vovo], outperms)
    update_code!(func, ein"aibk,jcld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, v₁_vovo], outperms)
    update_code!(func, ein"aicj,kbld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, v₁_vovo], outperms)
    update_code!(func, ein"ajck,ibld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, v₁_vovo], outperms)
    finalize_eT_function(func, "jacobian_transpose_s2", "qed_ccsd_2")
end

