let
    func = FortranFunction(("sigma_vovo", ["v", "o", "v", "o"]))
    outperms = [[1, 2, 3, 4], [3, 4, 1, 2]]
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    bγ2 = ("bγ2", true)
    bs_vo = ("bs_vo", true)
    d_ov = ("d_ov", true)
    bs2_vovo = ("bs2_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    ω = ("wf%qed%frequencies(wf%mode)", false)
    F_oo = ("F_oo", true)
    F_vv = ("F_vv", true)
    bs_vovo = ("bs_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    d_oo = ("d_oo", true)
    d_vv = ("d_vv", true)
    γ₁ = ("wf%s0", false)
    L_ovvo = ("L_ovvo", true)
    g_ovvo = ("g_ovvo", true)
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_oovv = ("g_oovv", true)
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₁_vo = ("wf%s1", false)
    t_vovo = ("t_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"iajb,->aibj", 2//1, [L_ovov, bγ2], outperms)
    update_code!(func, ein"ai,jb->aibj", 8//1, [bs_vo, d_ov], outperms)
    update_code!(func, ein"aj,ib->aibj", -4//1, [bs_vo, d_ov], outperms)
    update_code!(func, ein"aibj,->aibj", 2//1, [bs2_vovo, ω], outperms)
    update_code!(func, ein"ik,akbj->aibj", -2//1, [F_oo, bs2_vovo], outperms)
    update_code!(func, ein"ca,bjci->aibj", 2//1, [F_vv, bs2_vovo], outperms)
    update_code!(func, ein"aibj,kk->aibj", 2//1, [bs_vovo, d_oo], outperms)
    update_code!(func, ein"aibk,jk->aibj", -2//1, [bs_vovo, d_oo], outperms)
    update_code!(func, ein"aicj,cb->aibj", 2//1, [bs_vovo, d_vv], outperms)
    update_code!(func, ein"aibk,jk,->aibj", -2//1, [bs2_vovo, d_oo, γ₁], outperms)
    update_code!(func, ein"aicj,cb,->aibj", 2//1, [bs2_vovo, d_vv, γ₁], outperms)
    update_code!(func, ein"iack,bjck->aibj", 2//1, [L_ovvo, bs2_vovo], outperms)
    update_code!(func, ein"ajck,ibck->aibj", -2//1, [bs2_vovo, g_ovvo], outperms)
    update_code!(func, ein"akbl,ikjl->aibj", 1//1, [bs2_vovo, g_oooo], outperms)
    update_code!(func, ein"akcj,ikcb->aibj", -2//1, [bs2_vovo, g_oovv], outperms)
    update_code!(func, ein"cidj,cadb->aibj", 1//1, [bs2_vovo, g_vvvv], outperms)
    update_code!(func, ein"aibj,kc,ck->aibj", 4//1, [bs2_vovo, d_ov, s₁_vo], outperms)
    update_code!(func, ein"aibk,jc,ck->aibj", -6//1, [bs2_vovo, d_ov, s₁_vo], outperms)
    update_code!(func, ein"aicj,kb,ck->aibj", -6//1, [bs2_vovo, d_ov, s₁_vo], outperms)
    update_code!(func, ein"aick,jb,ck->aibj", 4//1, [bs2_vovo, d_ov, s₁_vo], outperms)
    update_code!(func, ein"ajck,ib,ck->aibj", -2//1, [bs2_vovo, d_ov, s₁_vo], outperms)
    update_code!(func, ein"iajc,bkdl,ckdl->aibj", -2//1, [L_ovov, bs2_vovo, t_vovo], outperms)
    update_code!(func, ein"iakb,cjdl,ckdl->aibj", -2//1, [L_ovov, bs2_vovo, t_vovo], outperms)
    update_code!(func, ein"iakc,bjdl,ckdl->aibj", 2//1, [L_ovov, bs2_vovo, u_vovo], outperms)
    update_code!(func, ein"ajck,idlb,ckdl->aibj", 2//1, [bs2_vovo, g_ovov, t_vovo], outperms)
    update_code!(func, ein"akbl,icjd,ckdl->aibj", 1//1, [bs2_vovo, g_ovov, t_vovo], outperms)
    update_code!(func, ein"akcj,idlb,cldk->aibj", 2//1, [bs2_vovo, g_ovov, t_vovo], outperms)
    update_code!(func, ein"cidj,kalb,ckdl->aibj", 1//1, [bs2_vovo, g_ovov, t_vovo], outperms)
    update_code!(func, ein"aibk,jcld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, u_vovo], outperms)
    update_code!(func, ein"aicj,kbld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, u_vovo], outperms)
    update_code!(func, ein"ajck,ibld,ckdl->aibj", -2//1, [bs2_vovo, g_ovov, u_vovo], outperms)
    finalize_eT_function(func, "jacobian_transpose_s2_2", "qed_ccsd_2")
end

