let
    func = FortranFunction(("sigma_vo", ["v", "o"]))
    bs_vo = ("bs_vo", true)
    ω = ("wf%qed%frequencies(wf%mode)", false)
    bγ2 = ("bγ2", true)
    d_ov = ("d_ov", true)
    γ₂ = ("wf%s0_1", false)
    F_oo = ("F_oo", true)
    F_vv = ("F_vv", true)
    d_oo = ("d_oo", true)
    γ₁ = ("wf%s0", false)
    d_vv = ("d_vv", true)
    L_ovvo = ("L_ovvo", true)
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₁_vo = ("wf%s1", false)
    bs2_vovo = ("bs2_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₂_vo = ("wf%s1_2", false)
    F_ov = ("F_ov", true)
    s₁_vovo = ("s₁_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s₂_vovo = ("s₂_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    t_vovo = ("t_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    v₂_vovo = ("v₂_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_oovv = ("g_oovv", true)
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovvo = ("g_ovvo", true)
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_vvoo = ("g_vvoo", true)
    g_voov = ("g_voov", true)
    L_ovvv = ("L_ovvv", true)
    L_ovoo = ("L_ovoo", true)
    g_ovvv = ("g_ovvv", true)
    g_ovoo = ("g_ovoo", true)
    g_vvov = ("g_vvov", true)
    g_ooov = ("g_ooov", true)
    v₁_vovo = ("v₁_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"ai,->ai", 1//1, [bs_vo, ω])
    update_code!(func, ein",ia->ai", 4//1, [bγ2, d_ov])
    update_code!(func, ein",ia,->ai", 8//1, [bγ2, d_ov, γ₂])
    update_code!(func, ein"ij,aj->ai", -1//1, [F_oo, bs_vo])
    update_code!(func, ein"ba,bi->ai", 1//1, [F_vv, bs_vo])
    update_code!(func, ein"aj,ij,->ai", -1//1, [bs_vo, d_oo, γ₁])
    update_code!(func, ein"bi,ba,->ai", 1//1, [bs_vo, d_vv, γ₁])
    update_code!(func, ein"iabj,bj->ai", 1//1, [L_ovvo, bs_vo])
    update_code!(func, ein"iajb,,bj->ai", 4//1, [L_ovov, bγ2, s₁_vo])
    update_code!(func, ein"ai,jb,bj->ai", 2//1, [bs_vo, d_ov, s₁_vo])
    update_code!(func, ein"aj,ib,bj->ai", -2//1, [bs_vo, d_ov, s₁_vo])
    update_code!(func, ein"bi,ja,bj->ai", -2//1, [bs_vo, d_ov, s₁_vo])
    update_code!(func, ein"bj,ia,bj->ai", 2//1, [bs_vo, d_ov, s₁_vo])
    update_code!(func, ein"aibj,bc,cj->ai", 2//1, [bs2_vovo, d_vv, s₂_vo])
    update_code!(func, ein"aibj,kj,bk->ai", -2//1, [bs2_vovo, d_oo, s₂_vo])
    update_code!(func, ein"ajbk,ij,bk->ai", -4//1, [bs2_vovo, d_oo, s₂_vo])
    update_code!(func, ein"bicj,ba,cj->ai", 4//1, [bs2_vovo, d_vv, s₂_vo])
    update_code!(func, ein"ib,ajck,bjck->ai", -2//1, [F_ov, bs2_vovo, s₁_vovo])
    update_code!(func, ein"ja,bick,bjck->ai", -2//1, [F_ov, bs2_vovo, s₁_vovo])
    update_code!(func, ein"iajb,ck,bjck->ai", 1//1, [L_ovov, bs_vo, u_vovo])
    update_code!(func, ein"aj,ibkc,bjck->ai", -1//1, [bs_vo, g_ovov, u_vovo])
    update_code!(func, ein"bi,jakc,bjck->ai", -1//1, [bs_vo, g_ovov, u_vovo])
    update_code!(func, ein"ajbk,ic,bkcj->ai", -6//1, [bs2_vovo, d_ov, s₂_vovo])
    update_code!(func, ein"bicj,ka,bkcj->ai", -6//1, [bs2_vovo, d_ov, s₂_vovo])
    update_code!(func, ein"bjck,ia,bjck->ai", 4//1, [bs2_vovo, d_ov, s₂_vovo])
    update_code!(func, ein"ajbk,ic,bkcj->ai", -2//1, [bs2_vovo, d_ov, t_vovo])
    update_code!(func, ein"bicj,ka,bkcj->ai", -2//1, [bs2_vovo, d_ov, t_vovo])
    update_code!(func, ein"aibj,kc,bjck->ai", 2//1, [bs2_vovo, d_ov, v₂_vovo])
    update_code!(func, ein"ajbk,ijbc,ck->ai", -2//1, [bs2_vovo, g_oovv, s₁_vo])
    update_code!(func, ein"ajbk,ijlk,bl->ai", 2//1, [bs2_vovo, g_oooo, s₁_vo])
    update_code!(func, ein"ajbk,icbk,cj->ai", -2//1, [bs2_vovo, g_ovvo, s₁_vo])
    update_code!(func, ein"bicj,bacd,dj->ai", 2//1, [bs2_vovo, g_vvvv, s₁_vo])
    update_code!(func, ein"bicj,bakj,ck->ai", -2//1, [bs2_vovo, g_vvoo, s₁_vo])
    update_code!(func, ein"bicj,cjka,bk->ai", -2//1, [bs2_vovo, g_voov, s₁_vo])
    update_code!(func, ein"aibj,kc,bk,cj->ai", -2//1, [bs2_vovo, d_ov, s₁_vo, s₁_vo])
    update_code!(func, ein"ajbk,ic,bk,cj->ai", -2//1, [bs2_vovo, d_ov, s₁_vo, s₁_vo])
    update_code!(func, ein"bicj,ka,bk,cj->ai", -2//1, [bs2_vovo, d_ov, s₁_vo, s₁_vo])
    update_code!(func, ein"ajbk,ic,bkcj,->ai", -2//1, [bs2_vovo, d_ov, s₁_vovo, γ₁])
    update_code!(func, ein"bicj,ka,bkcj,->ai", -2//1, [bs2_vovo, d_ov, s₁_vovo, γ₁])
    update_code!(func, ein"ajbk,ic,bkcj,->ai", -4//1, [bs2_vovo, d_ov, t_vovo, γ₂])
    update_code!(func, ein"bicj,ka,bkcj,->ai", -4//1, [bs2_vovo, d_ov, t_vovo, γ₂])
    update_code!(func, ein"iabc,bjdk,cjdk->ai", 2//1, [L_ovvv, bs2_vovo, s₁_vovo])
    update_code!(func, ein"iajk,bkcl,bjcl->ai", -2//1, [L_ovoo, bs2_vovo, s₁_vovo])
    update_code!(func, ein"ajbk,icbd,cjdk->ai", -2//1, [bs2_vovo, g_ovvv, s₁_vovo])
    update_code!(func, ein"ajbk,iclj,bkcl->ai", 2//1, [bs2_vovo, g_ovoo, s₁_vovo])
    update_code!(func, ein"ajbk,iclk,blcj->ai", 2//1, [bs2_vovo, g_ovoo, s₁_vovo])
    update_code!(func, ein"bicj,bdka,cjdk->ai", -2//1, [bs2_vovo, g_vvov, s₁_vovo])
    update_code!(func, ein"bicj,cdka,bkdj->ai", -2//1, [bs2_vovo, g_vvov, s₁_vovo])
    update_code!(func, ein"bicj,kalj,bkcl->ai", 2//1, [bs2_vovo, g_ovoo, s₁_vovo])
    update_code!(func, ein"ajbk,ijlc,bkcl->ai", -2//1, [bs2_vovo, g_ooov, v₁_vovo])
    update_code!(func, ein"bicj,bakd,cjdk->ai", 2//1, [bs2_vovo, g_vvov, v₁_vovo])
    update_code!(func, ein"iajb,ckdl,bk,cjdl->ai", -2//1, [L_ovov, bs2_vovo, s₁_vo, t_vovo])
    update_code!(func, ein"iajb,ckdl,cj,bkdl->ai", -2//1, [L_ovov, bs2_vovo, s₁_vo, t_vovo])
    update_code!(func, ein"ibjc,akdl,cj,bkdl->ai", -2//1, [L_ovov, bs2_vovo, s₁_vo, t_vovo])
    update_code!(func, ein"jakb,cidl,bk,cjdl->ai", -2//1, [L_ovov, bs2_vovo, s₁_vo, t_vovo])
    update_code!(func, ein"ajbk,icld,bl,cjdk->ai", 2//1, [bs2_vovo, g_ovov, s₁_vo, t_vovo])
    update_code!(func, ein"ajbk,icld,dj,bkcl->ai", 2//1, [bs2_vovo, g_ovov, s₁_vo, t_vovo])
    update_code!(func, ein"ajbk,icld,dk,blcj->ai", 2//1, [bs2_vovo, g_ovov, s₁_vo, t_vovo])
    update_code!(func, ein"bicj,kald,bl,cjdk->ai", 2//1, [bs2_vovo, g_ovov, s₁_vo, t_vovo])
    update_code!(func, ein"bicj,kald,cl,bkdj->ai", 2//1, [bs2_vovo, g_ovov, s₁_vo, t_vovo])
    update_code!(func, ein"bicj,kald,dj,bkcl->ai", 2//1, [bs2_vovo, g_ovov, s₁_vo, t_vovo])
    update_code!(func, ein"ajbk,icld,cj,bkdl->ai", -2//1, [bs2_vovo, g_ovov, s₁_vo, u_vovo])
    update_code!(func, ein"bicj,kald,bk,cjdl->ai", -2//1, [bs2_vovo, g_ovov, s₁_vo, u_vovo])
    finalize_eT_function(func, "jacobian_transpose_s1", "qed_ccsd_2")
end

