let
    func = FortranFunction(("omega_vovo", ["v", "o", "v", "o"]))
    outperms = [[1, 2, 3, 4], [3, 4, 1, 2]]
    s₂_vovo = ("s₂_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    ω = ("wf%qed%frequencies(wf%mode)", false)
    F_vv = ("F_vv", true)
    F_oo = ("F_oo", true)
    d_vv = ("d_vv", true)
    s₁_vovo = ("s₁_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    d_oo = ("d_oo", true)
    g_vovv = ("g_vovv", true)
    s₂_vo = ("wf%s1_2", false)
    g_vooo = ("g_vooo", true)
    s₁_vo = ("wf%s1", false)
    γ₂ = ("wf%s0_1", false)
    γ₁ = ("wf%s0", false)
    g_vvvv = ("g_vvvv", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    L_J_vv = ("L_J_vv", true)
    g_vvoo = ("g_vvoo", true)
    g_oooo = ("g_oooo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_voov = ("g_voov", true)
    v₂_vovo = ("v₂_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    F_ov = ("F_ov", true)
    t_vovo = ("t_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    d_ov = ("d_ov", true)
    v₁_vovo = ("v₁_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    L_vvov = ("L_vvov", true)
    L_ooov = ("L_ooov", true)
    g_vvov = ("g_vvov", true)
    g_ooov = ("g_ooov", true)
    u_vovo = ("wf%u_aibj", false, [[1, 2, 3, 4], [3, 4, 1, 2]])
    g_ovov = ("g_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    L_ovov = ("L_ovov", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein"aibj,->aibj", 2//1, [s₂_vovo, ω], outperms)
    update_code!(func, ein"ac,bjci->aibj", 2//1, [F_vv, s₂_vovo], outperms)
    update_code!(func, ein"ki,akbj->aibj", -2//1, [F_oo, s₂_vovo], outperms)
    update_code!(func, ein"ac,bjci->aibj", 2//1, [d_vv, s₁_vovo], outperms)
    update_code!(func, ein"ki,akbj->aibj", -2//1, [d_oo, s₁_vovo], outperms)
    update_code!(func, ein"aibc,cj->aibj", 2//1, [g_vovv, s₂_vo], outperms)
    update_code!(func, ein"aikj,bk->aibj", -2//1, [g_vooo, s₂_vo], outperms)
    update_code!(func, ein"ac,bj,ci->aibj", 2//1, [d_vv, s₁_vo, s₂_vo], outperms)
    update_code!(func, ein"ac,ci,bj->aibj", 4//1, [d_vv, s₁_vo, s₂_vo], outperms)
    update_code!(func, ein"ki,ak,bj->aibj", -4//1, [d_oo, s₁_vo, s₂_vo], outperms)
    update_code!(func, ein"ki,bj,ak->aibj", -2//1, [d_oo, s₁_vo, s₂_vo], outperms)
    update_code!(func, ein"ac,bjci,->aibj", 4//1, [d_vv, s₁_vovo, γ₂], outperms)
    update_code!(func, ein"ki,akbj,->aibj", -4//1, [d_oo, s₁_vovo, γ₂], outperms)
    update_code!(func, ein"ac,bjci,->aibj", 2//1, [d_vv, s₂_vovo, γ₁], outperms)
    update_code!(func, ein"ki,akbj,->aibj", -2//1, [d_oo, s₂_vovo, γ₁], outperms)
    update_code!(func, ein"acbd,cidj->aibj", 1//1, [g_vvvv, s₂_vovo], outperms)
    update_code!(func, ein"acki,bjck->aibj", -2//1, [g_vvoo, s₂_vovo], outperms)
    update_code!(func, ein"ackj,bkci->aibj", -2//1, [g_vvoo, s₂_vovo], outperms)
    update_code!(func, ein"kilj,akbl->aibj", 1//1, [g_oooo, s₂_vovo], outperms)
    update_code!(func, ein"aikc,bjck->aibj", 2//1, [g_voov, v₂_vovo], outperms)
    update_code!(func, ein"kc,ak,bjci->aibj", -2//1, [F_ov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"kc,ci,akbj->aibj", -2//1, [F_ov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"kc,ak,bjci->aibj", -2//1, [F_ov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"kc,ci,akbj->aibj", -2//1, [F_ov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"kc,ak,bjci->aibj", -6//1, [d_ov, s₁_vo, s₂_vovo], outperms)
    update_code!(func, ein"kc,ci,akbj->aibj", -6//1, [d_ov, s₁_vo, s₂_vovo], outperms)
    update_code!(func, ein"kc,ck,aibj->aibj", 4//1, [d_ov, s₁_vo, s₂_vovo], outperms)
    update_code!(func, ein"kc,aibj,ck->aibj", 2//1, [d_ov, s₁_vovo, s₂_vo], outperms)
    update_code!(func, ein"kc,aibk,cj->aibj", -6//1, [d_ov, s₁_vovo, s₂_vo], outperms)
    update_code!(func, ein"kc,aicj,bk->aibj", -6//1, [d_ov, s₁_vovo, s₂_vo], outperms)
    update_code!(func, ein"kc,ak,bjci->aibj", -2//1, [d_ov, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kc,ci,akbj->aibj", -2//1, [d_ov, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kc,ai,bjck->aibj", 2//1, [d_ov, s₁_vo, v₂_vovo], outperms)
    update_code!(func, ein"kc,ai,bjck->aibj", 4//1, [d_ov, s₂_vo, v₁_vovo], outperms)
    update_code!(func, ein"aikc,bk,cj->aibj", -2//1, [g_voov, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"hac,hbd,ci,dj->aibj", 1//1, [L_J_vv, L_J_vv, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"ackj,bk,ci->aibj", -2//1, [g_vvoo, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"kilj,ak,bl->aibj", 1//1, [g_oooo, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"kc,ai,bk,cj->aibj", -2//1, [d_ov, s₁_vo, s₁_vo, s₁_vo], outperms)
    update_code!(func, ein"kc,ak,bjci,->aibj", -2//1, [d_ov, s₁_vo, s₁_vovo, γ₁], outperms)
    update_code!(func, ein"kc,ci,akbj,->aibj", -2//1, [d_ov, s₁_vo, s₁_vovo, γ₁], outperms)
    update_code!(func, ein"kc,ak,bjci,->aibj", -4//1, [d_ov, s₁_vo, t_vovo, γ₂], outperms)
    update_code!(func, ein"kc,ci,akbj,->aibj", -4//1, [d_ov, s₁_vo, t_vovo, γ₂], outperms)
    update_code!(func, ein"kc,ak,bjci,->aibj", -2//1, [d_ov, s₂_vo, t_vovo, γ₁], outperms)
    update_code!(func, ein"kc,ci,akbj,->aibj", -2//1, [d_ov, s₂_vo, t_vovo, γ₁], outperms)
    update_code!(func, ein"ackd,dk,bjci->aibj", 2//1, [L_vvov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"kilc,cl,akbj->aibj", -2//1, [L_ooov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"ackd,dk,bjci->aibj", 2//1, [L_vvov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"kilc,cl,akbj->aibj", -2//1, [L_ooov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"ackd,bk,cidj->aibj", -2//1, [g_vvov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"ackd,di,bjck->aibj", -2//1, [g_vvov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"ackd,dj,bkci->aibj", -2//1, [g_vvov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"kilc,al,bjck->aibj", 2//1, [g_ooov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"kilc,bl,akcj->aibj", 2//1, [g_ooov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"kilc,cj,akbl->aibj", 2//1, [g_ooov, s₁_vo, s₁_vovo], outperms)
    update_code!(func, ein"ackd,ci,bjdk->aibj", 2//1, [g_vvov, s₁_vo, v₁_vovo], outperms)
    update_code!(func, ein"kilc,ak,bjcl->aibj", -2//1, [g_ooov, s₁_vo, v₁_vovo], outperms)
    update_code!(func, ein"ackd,bk,cidj->aibj", -2//1, [g_vvov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"ackd,di,bjck->aibj", -2//1, [g_vvov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"ackd,dj,bkci->aibj", -2//1, [g_vvov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"kilc,al,bjck->aibj", 2//1, [g_ooov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"kilc,bl,akcj->aibj", 2//1, [g_ooov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"kilc,cj,akbl->aibj", 2//1, [g_ooov, s₂_vo, t_vovo], outperms)
    update_code!(func, ein"ackd,ci,bjdk->aibj", 2//1, [g_vvov, s₂_vo, u_vovo], outperms)
    update_code!(func, ein"kilc,ak,bjcl->aibj", -2//1, [g_ooov, s₂_vo, u_vovo], outperms)
    update_code!(func, ein"kcld,aicl,bkdj->aibj", 1//1, [g_ovov, s₁_vovo, s₁_vovo], outperms)
    update_code!(func, ein"kcld,akbl,cidj->aibj", 1//1, [g_ovov, s₁_vovo, s₁_vovo], outperms)
    update_code!(func, ein"kcld,akdj,blci->aibj", 1//1, [g_ovov, s₁_vovo, s₁_vovo], outperms)
    update_code!(func, ein"kcld,aibk,cjdl->aibj", -2//1, [g_ovov, s₁_vovo, v₁_vovo], outperms)
    update_code!(func, ein"kcld,aicj,bkdl->aibj", -2//1, [g_ovov, s₁_vovo, v₁_vovo], outperms)
    update_code!(func, ein"kcld,bjcl,aidk->aibj", -1//1, [g_ovov, s₁_vovo, v₁_vovo], outperms)
    update_code!(func, ein"kcld,akbl,cidj->aibj", 1//1, [g_ovov, s₂_vovo, t_vovo], outperms)
    update_code!(func, ein"kcld,akdi,bjcl->aibj", 2//1, [g_ovov, s₂_vovo, t_vovo], outperms)
    update_code!(func, ein"kcld,akdj,blci->aibj", 2//1, [g_ovov, s₂_vovo, t_vovo], outperms)
    update_code!(func, ein"kcld,cidj,akbl->aibj", 1//1, [g_ovov, s₂_vovo, t_vovo], outperms)
    update_code!(func, ein"kcld,aibk,cjdl->aibj", -2//1, [g_ovov, s₂_vovo, u_vovo], outperms)
    update_code!(func, ein"kcld,aicj,bkdl->aibj", -2//1, [g_ovov, s₂_vovo, u_vovo], outperms)
    update_code!(func, ein"kcld,aicl,bjdk->aibj", -2//1, [g_ovov, s₂_vovo, u_vovo], outperms)
    update_code!(func, ein"kcld,aibk,cjdl->aibj", -2//1, [g_ovov, t_vovo, v₂_vovo], outperms)
    update_code!(func, ein"kcld,aicj,bkdl->aibj", -2//1, [g_ovov, t_vovo, v₂_vovo], outperms)
    update_code!(func, ein"kcld,aick,bjdl->aibj", 2//1, [g_ovov, u_vovo, v₂_vovo], outperms)
    update_code!(func, ein"kcld,aick,bjdl->aibj", 1//1, [g_ovov, v₁_vovo, v₁_vovo], outperms)
    update_code!(func, ein"kcld,ak,dl,bjci->aibj", -2//1, [L_ovov, s₁_vo, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kcld,ci,dl,akbj->aibj", -2//1, [L_ovov, s₁_vo, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kcld,ak,bl,cidj->aibj", 1//1, [g_ovov, s₁_vo, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kcld,ak,di,bjcl->aibj", 2//1, [g_ovov, s₁_vo, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kcld,ak,dj,blci->aibj", 2//1, [g_ovov, s₁_vo, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kcld,ci,dj,akbl->aibj", 1//1, [g_ovov, s₁_vo, s₁_vo, t_vovo], outperms)
    update_code!(func, ein"kcld,ak,ci,bjdl->aibj", -2//1, [g_ovov, s₁_vo, s₁_vo, u_vovo], outperms)
    finalize_eT_function(func, "omega_2_aibj", "qed_ccsd_2")
end

