let
    func = FortranFunction(("D", String[]))
    Ls1 = ("Ls1", true)
    Rs = ("Rs", true)
    γ₁ = ("s0", true)
    Ls_vo = ("Ls_vo", true)
    Rt_vo = ("Rt_vo", true)
    Lt_vo = ("Lt_vo", true)
    Rs_vo = ("Rs_vo", true)
    s_vo = ("s_vo", true)
    Ls_vovo = ("Ls_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    Rt_vovo = ("Rt_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    Lt_vovo = ("Lt_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    Rs_vovo = ("Rs_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    s_vovo = ("s_vovo", true, [[1, 2, 3, 4], [3, 4, 1, 2]])
    update_code!(func, ein",,->", 2//1, [Ls1, Rs, γ₁])
    update_code!(func, ein"ai,ai->", 2//1, [Ls_vo, Rt_vo])
    update_code!(func, ein"ai,ai->", 2//1, [Lt_vo, Rs_vo])
    update_code!(func, ein"ai,,ai->", 2//1, [Ls_vo, Rs, s_vo])
    update_code!(func, ein"ai,ai,->", 2//1, [Ls_vo, Rs_vo, γ₁])
    update_code!(func, ein"ai,ai,->", 2//1, [Lt_vo, Rt_vo, γ₁])
    update_code!(func, ein"aibj,aibj->", 1//1, [Ls_vovo, Rt_vovo])
    update_code!(func, ein"aibj,aibj->", 1//1, [Lt_vovo, Rs_vovo])
    update_code!(func, ein"aibj,,aibj->", 1//1, [Ls_vovo, Rs, s_vovo])
    update_code!(func, ein"aibj,ai,bj->", 2//1, [Ls_vovo, Rs_vo, s_vo])
    update_code!(func, ein"aibj,aibj,->", 1//1, [Ls_vovo, Rs_vovo, γ₁])
    update_code!(func, ein"aibj,ai,bj->", 2//1, [Lt_vovo, Rt_vo, s_vo])
    update_code!(func, ein"aibj,aibj,->", 1//1, [Lt_vovo, Rt_vovo, γ₁])
    finalize_eT_function(func, "density_1e_1b_qed_ccsd_mu_nu_oo_diagonal_terms_qed_ccsd", "qed_ccsd")
end

